#!/usr/bin/env node
/**
 * ABSIS Capital Sync — Member Migration Script (Node.js)
 * Restores organizations/{orgId}/members/{uid} subcollection docs
 * from exported user data.
 *
 * Usage:
 *   1. Install: npm install firebase-admin
 *   2. Download your Firebase service account key from:
 *      Firebase Console → Project Settings → Service accounts → Generate new private key
 *   3. Save it as serviceAccountKey.json in the same folder as this script
 *   4. Run: node migrate_members.js
 *
 * This script is SAFE to run multiple times — it uses set() with merge: true,
 * so existing documents are updated, not overwritten.
 *
 * Changes vs. original Python script:
 *   - Adds ALL fields from the exported Excel (dob, bloodGroup, fatherName,
 *     motherName, nid, occupation, address, driveFolderId, activeOrgId, etc.)
 *   - Skips photoURL (base64 blobs — stored separately in Drive)
 *   - Uses Promise.all for concurrent writes per member
 */

const admin = require("firebase-admin");
const serviceAccount = require("./serviceAccountKey.json");

// ── Init ─────────────────────────────────────────────────────────────────────
admin.initializeApp({ credential: admin.credential.cert(serviceAccount) });
const db = admin.firestore();

// ── Member data (all fields from exported Excel) ──────────────────────────────
const MEMBERS = [
  {
    uid: "4QOqC8MyaWPDjvwuacyPECFl8Ir1",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "",
    role: "member",
    nameEnglish: "Rumana Yesmin",
    nameBangla: "রুমানা ইয়াসমিন",
    nameBengali: "রুমানা ইয়াসমিন",
    phone: "01740469793",
    email: "ryssrv@gmail.com",
    joinedAt: "2026-04-07T08:21:30.004Z",
    dob: "1997-07-29",
    bloodGroup: "AB+",
    fatherNameEn: "MD Abdur Rahman",
    fatherNameBn: "",
    motherNameEn: "Sufia Begum",
    motherNameBn: "",
    nid: "",
    occupation: "Housewife",
    presentAddressEn: "Kajipara, Saidpur, Nilphamari",
    presentAddressBn: "",
    driveFolderId: "",
  },
  {
    uid: "4y94U1rbjTThuuvHncOLxecMNtw1",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "A-012",
    role: "member",
    nameEnglish: "MD ABDULLAH Al Shahadot Hossain",
    nameBangla: "মো: আব্দুল্লাহ আল শাহাদত হোসেন",
    nameBengali: "মো: আব্দুল্লাহ আল শাহাদত হোসেন",
    phone: "+8801767030990",
    email: "shuvotex75@gmail.com",
    joinedAt: "2026-04-06T12:01:36.306Z",
    dob: "1991-11-05",
    bloodGroup: "O+",
    fatherNameEn: "MD Anowar Hossain",
    fatherNameBn: "",
    motherNameEn: "Mst Sherina",
    motherNameBn: "",
    nid: "2354073021",
    occupation: "Private Job",
    presentAddressEn: "",
    presentAddressBn: "কাজিপাড়া সৈয়দপুর নীলফামারী",
    driveFolderId: "1evniU5_WxxG_C36M10baeDQAJBoKKCx_",
  },
  {
    uid: "6L3JuyEZKoVDMybJ3FDxOV12Z5r2",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "A-004",
    role: "member",
    nameEnglish: "GAYLAN IBNA WAHID",
    nameBangla: "গায়লান ইবনে ওয়াহিদ",
    nameBengali: " গায়লান ইবনে ওয়াহিদ ",
    phone: "01787495301",
    email: "gaylanibnewahid201@gmail.com",
    joinedAt: "2026-04-01T15:34:09.088Z",
    dob: "1999-09-21",
    bloodGroup: "AB+",
    fatherNameEn: "MD.WAHIDUL HAQUE SARKER",
    fatherNameBn: "",
    motherNameEn: "GULSHAN ARA",
    motherNameBn: "",
    nid: "6454535698",
    occupation: "Assistant Engineer",
    presentAddressEn: "Modhurampur,Taragonj,Rangpur",
    presentAddressBn: "",
    driveFolderId: "1_xA8zhUhkhadK4TOGavgcpSrXvZoduMS",
  },
  {
    uid: "7eM6FQN1AvfxEmdHDtdnxZOfYKc2",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "A-007",
    role: "member",
    nameEnglish: "Md Dulal Hossain",
    nameBangla: "মো: দুলাল হোসেন",
    nameBengali: "মো: দুলাল হোসেন",
    phone: "01727053647",
    email: "hdulal26@gmail.com",
    joinedAt: "2026-04-04T10:04:34.724Z",
    dob: "1999-07-16",
    bloodGroup: "A-",
    fatherNameEn: "Md Matiar Rahman",
    fatherNameBn: "",
    motherNameEn: "Dulali Begum",
    motherNameBn: "",
    nid: "4206563787",
    occupation: "Medical Technician",
    presentAddressEn:
      "Kasiram Belpukur (Nayabari),Hazari Hat-5310,Saidpur,Nilphamari",
    presentAddressBn: "",
    driveFolderId: "1hgpry1bgM4fABsasRTxo_jkKxxDDjoUP",
  },
  {
    uid: "8mFIT3Ay0pToCQbQKM8Gnek0OYt2",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "",
    role: "superadmin",
    nameEnglish: "Al-Barakah",
    nameBangla: "আল-বারাকাহ",
    nameBengali: "আল-বারাকাহ",
    phone: "",
    email: "",
    joinedAt: "",
    dob: "",
    bloodGroup: "",
    fatherNameEn: "",
    fatherNameBn: "",
    motherNameEn: "",
    motherNameBn: "",
    nid: "",
    occupation: "",
    presentAddressEn: "",
    presentAddressBn: "",
    driveFolderId: "",
  },
  {
    uid: "9CQo2KU1FjV81NRsBQmwQ9mchf52",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "A-006",
    role: "member",
    nameEnglish: "MD.Shimul khan",
    nameBangla: "মোঃ শিমুল খান",
    nameBengali: "মো:শিমুল খান ",
    phone: "01751127773",
    email: "shimulk974@gmail.com",
    joinedAt: "2026-04-01T14:44:37.872Z",
    dob: "1999-10-24",
    bloodGroup: "B+",
    fatherNameEn: "",
    fatherNameBn: "মো: সিরাজুল ইসলাম",
    motherNameEn: "",
    motherNameBn: "মোছা: শাহানাজ পারভীন",
    nid: "1964487910",
    occupation: "",
    presentAddressEn:
      "Green city,East dendabor, pollibidut ,asuliya ,savar",
    presentAddressBn: "",
    driveFolderId: "1jYnqYuQUxC5An95cai2wnIjFvWaBVKrG",
  },
  {
    uid: "BqmGPHbB3DYRrH7MC7IYK9b7d922",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "",
    role: "member",
    nameEnglish: "MD. RABBE HOSSAIN",
    nameBangla: "মোঃ রাব্বি হোসেন",
    nameBengali: "মোঃ রাব্বি হোসেন",
    phone: "01965626344",
    email: "rabbehossainripon581013@gmail.com",
    joinedAt: "2026-04-14T05:52:24.356Z",
    dob: "1997-07-14",
    bloodGroup: "AB+",
    fatherNameEn: "MD. JABADUL",
    fatherNameBn: "",
    motherNameEn: "ASIA BEGUM",
    motherNameBn: "",
    nid: "1503331785",
    occupation: "PRAIVET TUTOR",
    presentAddressEn: "Biman Bondor Chaudhuripara,Saidpur,Nilphamari",
    presentAddressBn: "",
    driveFolderId: "",
  },
  {
    uid: "Bwor5PPXojMwVe3rT3RctKjKJaj1",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "A-008",
    role: "member",
    nameEnglish: "Nazmul Islam",
    nameBangla: "নাজমুল ইসলাম",
    nameBengali: "নাজমুল ইসলাম ",
    phone: "01883644361",
    email: "nazmulan09@gmail.com",
    joinedAt: "2026-04-09T12:41:19.848Z",
    dob: "1999-08-28",
    bloodGroup: "A+",
    fatherNameEn: "Md Nurul Alam",
    fatherNameBn: "",
    motherNameEn: "Manowara Begum",
    motherNameBn: "",
    nid: "2854433667",
    occupation: "Service holder",
    presentAddressEn: "",
    presentAddressBn: "",
    driveFolderId: "1WnJiuqLN-QtT4E0VC5HhejTkc3-F4M0q",
  },
  {
    uid: "G36jmQySKRax9al8mqgzpvvLO7B2",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "",
    role: "member",
    nameEnglish: "Md. Shahin Alam",
    nameBangla: "মো: শাহিন আলম",
    nameBengali: " মো: শাহিন আলম",
    phone: "01521114572",
    email: "samehedi344@gmail.com",
    joinedAt: "2026-04-11T03:56:32.036Z",
    dob: "2000-12-05",
    bloodGroup: "B-",
    fatherNameEn: "Md. Ruhul Amin",
    fatherNameBn: "",
    motherNameEn: "Mst. Shahanaj Amin",
    motherNameBn: "",
    nid: "1512587575",
    occupation: "Teacher",
    presentAddressEn: "Dhamoirhat, Naogaon",
    presentAddressBn: "",
    driveFolderId: "",
  },
  {
    uid: "KrmujHeoUJO1yWVmDd51C5JiSBl2",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "A-016",
    role: "member",
    nameEnglish: "Mehedi Hassan",
    nameBangla: "মেহেদী হাসান",
    nameBengali: "মেহেদী হাসান",
    phone: "01777448524",
    email: "mehedi67419461@gmail.com",
    joinedAt: "2026-04-14T04:46:17.270Z",
    dob: "1999-01-25",
    bloodGroup: "O+",
    fatherNameEn: "Mostafizur Rahman",
    fatherNameBn: "",
    motherNameEn: "Saleha khatun",
    motherNameBn: "",
    nid: "6454455707",
    occupation: "Business",
    presentAddressEn: "Old babu para",
    presentAddressBn: "",
    driveFolderId: "",
  },
  {
    uid: "LPDVJeRcPYgnF7sa7nlmLM9S3g52",
    orgs: ["org_1775011423121", "org_1775309545687", "org_1776435138950"],
    activeOrgId: "org_1775011423121",
    idNo: "A-001",
    role: "admin",
    nameEnglish: "MD. HABIBUL HASAN",
    nameBangla: "মোঃ হাবিবুল হাসান",
    nameBengali: "মোঃ হাবিবুল হাসান",
    phone: "01601767234",
    email: "habibulhaasan@gmail.com",
    joinedAt: "2026-04-01T02:43:05.088Z",
    dob: "2000-02-11",
    bloodGroup: "A+",
    fatherNameEn: "MD. ANWER HOSEN",
    fatherNameBn: "",
    motherNameEn: "ROWSAHN ARA BEGUM",
    motherNameBn: "",
    nid: "1030705774",
    occupation: "Service",
    presentAddressEn: "Banirapara, Azizroad, Sadipur, Nilphamari",
    presentAddressBn: "",
    driveFolderId: "1JjVN76K5LM_CUrDNh8bMxYmN4TDvIdjO",
  },
  {
    uid: "W4mBujfxzrOe7nRLlMuzfQzoZn13",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "",
    role: "member",
    nameEnglish: "Mahadi Hasan Moon",
    nameBangla: "মেহেদী হাসান মুন",
    nameBengali: "মেহেদী হাসান মুন",
    phone: "01797692420",
    email: "imehedi649@gmail.com",
    joinedAt: "2026-04-07T04:19:52.832Z",
    dob: "1997-04-15",
    bloodGroup: "B+",
    fatherNameEn: "Md Mohir Uddin",
    fatherNameBn: "",
    motherNameEn: "Laily Begum",
    motherNameBn: "",
    nid: "7803364269",
    occupation: "",
    presentAddressEn: "New babu para,saudpur",
    presentAddressBn: "",
    driveFolderId: "",
  },
  {
    uid: "YwGCGh5TajTnzAwHKh6cgn8Xxs63",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "A-003",
    role: "member",
    nameEnglish: "MD RAISUL ISLAM",
    nameBangla: "মোঃ রাইসুল ইসলাম",
    nameBengali: "মোঃ রাইসুল ইসলাম ",
    phone: "01724077921",
    email: "raisuli030@gmail.com",
    joinedAt: "2026-04-01T13:01:38.323Z",
    dob: "1999-02-12",
    bloodGroup: "B+",
    fatherNameEn: "Late ELIAS HOSSAIN",
    fatherNameBn: "",
    motherNameEn: "REHENA PARVIN",
    motherNameBn: "",
    nid: "3304476223",
    occupation: "SELF EMPLOYED",
    presentAddressEn: "Nichucoloni,Saidpur,Nilphamari",
    presentAddressBn: "",
    driveFolderId: "",
  },
  {
    uid: "gdIUdIlazvSK1XffNQZez5BJJXz2",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "A-002",
    role: "member",
    nameEnglish: "Rakybul Islam",
    nameBangla: "রাকিবুল ইসলাম",
    nameBengali: "রাকিবুল ইসলাম",
    phone: "01994639146",
    email: "rakybulislam1017@gmail.com",
    joinedAt: "2026-04-01T02:52:12.922Z",
    dob: "2000-03-05",
    bloodGroup: "O+",
    fatherNameEn: "Md. Azizur Rahman",
    fatherNameBn: "",
    motherNameEn: "Jorina khaton",
    motherNameBn: "",
    nid: "3760999866",
    occupation: "Madrasha Teacher",
    presentAddressEn: "Nichucolony, Saidpur, Nilphamari",
    presentAddressBn: "",
    driveFolderId: "",
  },
  {
    uid: "ildCXXA0KCNvaEVz4ke97FzPEUw2",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "A-011",
    role: "member",
    nameEnglish: "MD. ROCKYBUL ISLAM",
    nameBangla: "মোঃ রকিবুল ইসলাম",
    nameBengali: "মোঃ রকিবুল ইসলাম ",
    phone: "01739729375",
    email: "mdrockybuli24@gmail.com",
    joinedAt: "2026-04-06T13:53:11.162Z",
    dob: "1990-11-21",
    bloodGroup: "B+",
    fatherNameEn: "ABU SALAH",
    fatherNameBn: "",
    motherNameEn: "RAHIMA KHATUN",
    motherNameBn: "",
    nid: "",
    occupation: "Surveyer",
    presentAddressEn: "Baniapara, Saidpur, Nilphamari",
    presentAddressBn: "",
    driveFolderId: "",
  },
  {
    uid: "jQFNbnkKs2XPHRBAcoVb3r27SKZ2",
    orgs: ["org_1775373615522", "org_1775011423121"],
    activeOrgId: "org_1775373615522",
    idNo: "",
    role: "member",
    nameEnglish: "Md monowar hossain",
    nameBangla: "",
    nameBengali: "",
    phone: "01842138311",
    email: "mdmonowar8311@gmail.com",
    joinedAt: "2026-04-05T07:16:24.774Z",
    dob: "1991-10-17",
    bloodGroup: "O+",
    fatherNameEn: "Nur Mohammed",
    fatherNameBn: "",
    motherNameEn: "Anwara begum",
    motherNameBn: "",
    nid: "2852167242",
    occupation: "Job",
    presentAddressEn: "Khagrachari Panchari",
    presentAddressBn: "",
    driveFolderId: "",
  },
  {
    uid: "qB8IycXbtOXci9eE2NjI7GVdaw22",
    orgs: ["org_1775011423121"],
    activeOrgId: "org_1775011423121",
    idNo: "A-009",
    role: "member",
    nameEnglish: "Kawser Ahmed",
    nameBangla: "কাওছার আহমেদ",
    nameBengali: "কাওছার আহমেদ",
    phone: "+8801710302513",
    email: "kawser.ahmed.dev@gmail.com",
    joinedAt: "2026-04-01T06:45:50.691Z",
    dob: "1999-12-15",
    bloodGroup: "O+",
    fatherNameEn: "Md Abdul Quddus",
    fatherNameBn: "",
    motherNameEn: "Zahura Khatun",
    motherNameBn: "",
    nid: "8253992211",
    occupation: "Software engineer",
    presentAddressEn:
      "Village: Horihorpur, Post office: Astomonisha, Thana: Bhangura, District: Pabna, Division: Rajshahi",
    presentAddressBn: "",
    driveFolderId: "1vyAH_8yAu3kBohkl30loUXIiI0jvR0SW",
  },
  {
    uid: "r56mjgMz7Xb8KxmNIckGm0licIo2",
    orgs: ["org_1775875710938", "org_1775011423121"],
    activeOrgId: "org_1775875710938",
    idNo: "A-014",
    role: "member",
    nameEnglish: "Md Bashir Uddin",
    nameBangla: "মোঃ বশির উদ্দিন",
    nameBengali: "মোঃ বশির উদ্দিন ",
    phone: "01933939793",
    email: "bashiruddin.me2019@gmail.com",
    joinedAt: "2026-04-11T02:12:03.997Z",
    dob: "",
    bloodGroup: "A+",
    fatherNameEn: "Md Kuddus Mollah",
    fatherNameBn: "",
    motherNameEn: "Mrs.Khadaja Begum",
    motherNameBn: "",
    nid: "5104436984",
    occupation: "govenment Job holder",
    presentAddressEn: "Cantonment, Nichukoloni",
    presentAddressBn: "",
    driveFolderId: "",
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Remove empty-string values to keep Firestore clean, but always keep `approved`. */
function buildDoc(m) {
  const raw = {
    approved: true,
    role: m.role,
    idNo: m.idNo,
    activeOrgId: m.activeOrgId,
    nameEnglish: m.nameEnglish,
    nameBangla: m.nameBangla,
    nameBengali: m.nameBengali,
    phone: m.phone,
    email: m.email,
    dob: m.dob,
    bloodGroup: m.bloodGroup,
    fatherNameEn: m.fatherNameEn,
    fatherNameBn: m.fatherNameBn,
    motherNameEn: m.motherNameEn,
    motherNameBn: m.motherNameBn,
    nid: m.nid,
    occupation: m.occupation,
    presentAddressEn: m.presentAddressEn,
    presentAddressBn: m.presentAddressBn,
    driveFolderId: m.driveFolderId,
  };

  // Strip empty strings (but keep `approved: true` always)
  const doc = { approved: true };
  for (const [k, v] of Object.entries(raw)) {
    if (k !== "approved" && v !== "") doc[k] = v;
  }
  return doc;
}

// ── Run migration ─────────────────────────────────────────────────────────────
async function migrate() {
  console.log("Starting migration...\n");
  let total = 0;

  for (const m of MEMBERS) {
    const doc = buildDoc(m);

    // Write to all orgs this member belongs to (concurrent)
    const writes = m.orgs.map((orgId) => {
      const ref = db
        .collection("organizations")
        .doc(orgId)
        .collection("members")
        .doc(m.uid);

      return ref.set(doc, { merge: true }).then(() => {
        console.log(`  ✓ ${orgId}/members/${m.uid}  (${m.nameEnglish})`);
        total++;
      });
    });

    await Promise.all(writes);
  }

  console.log(`\nDone — ${total} member doc(s) written.`);
  process.exit(0);
}

migrate().catch((err) => {
  console.error("Migration failed:", err);
  process.exit(1);
});
